### ISSUE TITLE
ImportError: No module named 'sipdistutils'

### ISSUE THREAD

**Issue by lutzhorn** [wbsoft/python-poppler-qt5#14]
On **Ubuntu 16.04LTS** in a **virtualenv**, building `python-poppler-qt5` fails:

```
$ cd python-poppler-qt5
$ python3.5 setup.py build
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    import sipdistutils
ImportError: No module named 'sipdistutils'
```

But `sip` is installed:

```
$ pip3 freeze | grep sip
sip==4.19.1
```

What am I missing?

**Comment by syntaxaire** [comment]
The same problem is preventing me from even ```pip install```ing python-poppler-qt5.
Running this in a venv called 'frescobaldi' with sip installed:
```
(frescobaldi) syntaxaire@ubuntu:~/Python/frescobaldi$ python --version
Python 3.6.1
(frescobaldi) syntaxaire@ubuntu:~/Python/frescobaldi$ pip list
pip (9.0.1)
PyQt5 (5.8.2)
python-ly (0.9.5)
setuptools (28.8.0)
sip (4.19.2)
(frescobaldi) syntaxaire@ubuntu:~/Python/frescobaldi$ pip install python-poppler-qt5
Collecting python-poppler-qt5
  Using cached python-poppler-qt5-0.24.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-60rugen8/python-poppler-qt5/setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-60rugen8/python-poppler-qt5/```

**Comment by chamcha** [comment]
i also have the same issue. 

i hope this problem will be fix soon.

**Comment by francescpuig7** [comment]
I see that the issue remains open, and I have the same error on Windows 10 x64

My environment:
```Python 3.6
PyQt5==5.7.1
Sip == 4.9.12```

**Comment by jcnengel** [comment]
You might want to consider installing the development package for python-sip. This is required for building.

**Comment by tmattio** [comment]
It seems like the pip version of sip does not install sipdistutils. To install it from source, you can do that:

```
wget https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.3/sip-4.19.3.tar.gz
tar zxvf sip-4.19.3.tar.gz
cd sip-4.19.3
python configure.py
make
make install
```

**Comment by s-m-e** [comment]
You can get the sipdistutils.py from riverbank's mercurial server, i.e. [from here](https://www.riverbankcomputing.com/hg/sip/file/14685a6e736e/sipdistutils.py). It is self-contained. Just place it into your Python site-packages folder ...

**Comment by sincere-music** [comment]
This issue is driving me nuts, TBH. I followed the suggestion in the last comment, but it doesn’t change anything about the error message from Frescobaldi:

```
~$ frescobaldiTraceback (most recent call last):
  File "/usr/local/bin/frescobaldi", line 7, in <module>
    import main
  File "/usr/local/lib/python3.6/site-packages/frescobaldi_app/main.py", line 25, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
```

**Comment by ccmaass** [comment]
sincere-music, are you installing sip to python2 by any chance? Unless your default python is 3.x, you have to replace 'python' by python3 in tmattio's suggestion.

**Comment by sincere-music** [comment]
Thanks ccmaass, that really got me a large step forward.
Unfortunately, with that step I’m still not at the goal:

```
~$ frescobaldi
Traceback (most recent call last):
  File "/usr/local/bin/frescobaldi", line 7, in <module>
    import main
  File "/usr/local/lib/python3.6/site-packages/frescobaldi_app/main.py", line 33, in <module>
    from PyQt5.QtCore import QSettings, QTimer, QUrl
ModuleNotFoundError: No module named 'PyQt5'
~$ sudo -H pip3 install pyqt5
Collecting pyqt5
  Downloading PyQt5-5.9-5.9.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (104.6MB)
    100% |████████████████████████████████| 104.6MB 9.5kB/s 
Collecting sip<4.20,>=4.19.3 (from pyqt5)
  Downloading sip-4.19.3-cp35-cp35m-manylinux1_x86_64.whl (63kB)
    100% |████████████████████████████████| 71kB 1.3MB/s 
Installing collected packages: sip, pyqt5
  Found existing installation: sip 4.19.2
    Uninstalling sip-4.19.2:
      Successfully uninstalled sip-4.19.2
Successfully installed pyqt5-5.9 sip-4.19.3
~$ frescobaldi
Traceback (most recent call last):
  File "/usr/local/bin/frescobaldi", line 7, in <module>
    import main
  File "/usr/local/lib/python3.6/site-packages/frescobaldi_app/main.py", line 33, in <module>
    from PyQt5.QtCore import QSettings, QTimer, QUrl
ModuleNotFoundError: No module named 'PyQt5'
```

How should I go about to make Python 3.6 find PyQt5?

**Comment by sincere-music** [comment]
Some more chapters to the story: I noticed that pip wasn’t at the most recent version, and after an awful many turns (including recompiling python3.6 to circumvent an issue with zlib – I can’t believe those things are so convoluted…) I have a python3.6 and matching pip that seem to work fine…
… except:

```
~$ frescobaldi
Traceback (most recent call last):
  File "/usr/local/bin/frescobaldi", line 4, in <module>
    from frescobaldi_app import toplevel
ModuleNotFoundError: No module named 'frescobaldi_app'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/frescobaldi", line 4, in <module>
    from frescobaldi_app import toplevel
ModuleNotFoundError: No module named 'frescobaldi_app'
```

**Comment by sincere-music** [comment]
I did find this: https://stackoverflow.com/questions/45012581/how-to-import-python3-lib-in-python3-6, but the virtual environment part doesn’t apply to my use case at all.

**Comment by sincere-music** [comment]
I continue digging and hitting more dead ends. Sorry if the following contains _too much_ information.

I’m on a pristine Ubuntu 17.10 (that is with Python3.6) right now. From the frescobaldi download page and pages linked there I gathered that the following should absolutely be the correct way to do this:

```
sudo apt-get update
sudo apt install python3-setuptools
sudo easy_install3 pip
sudo [-H] pip3 install PyQt5
sudo [-H] pip3 install python-ly
cd ~
wget --show-progress https://github.com/wbsoft/frescobaldi/releases/download/v3.0.0/frescobaldi-3.0.0.tar.gz
tar -xzf frescobaldi-3.0.0.tar.gz
rm frescobaldi-3.0.0.tar.gz
sudo apt-get install pkg-config
wget https://github.com/wbsoft/python-poppler-qt5/archive/master.zip
unzip master.zip
rm master.zip
mv -T python-poppler-qt5-master/ python-poppler-qt5/
cd python-poppler-qt5/
python3 setup.py build
```
Now, this is the point where it fails (regardless if I use python or python3 for the last command) with
    ImportError: No module named sipdistutils
So far, so known problem.
I followed tmattio’s suggestion from above, tried to install sip from source using python3 instead of python, and on the first run of make I got this:

```
$ make
make[1]: Entering directory '/home/ubuntu/sip-4.19.3/sipgen'
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o main.o main.c
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o transform.o transform.c
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o gencode.o gencode.c
gencode.c: In function ‘generateNamedBaseType’:
gencode.c:9426:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
             nr_derefs = 1;
             ~~~~~~~~~~^~~
gencode.c:9430:9: note: here
         case byte_type:
         ^~~~
gencode.c:9484:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
             nr_derefs = 1;
             ~~~~~~~~~~^~~
gencode.c:9488:9: note: here
         case fake_void_type:
         ^~~~
gencode.c: In function ‘generateTupleBuilder’:
gencode.c:8573:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (copyConstRefArg(ad))
                ^
gencode.c:8581:9: note: here
         case fake_void_type:
         ^~~~
gencode.c: In function ‘generateHandleResult’:
gencode.c:12088:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if (ad->u.ed->fqcname != NULL)
            ^
gencode.c:12099:5: note: here
     case byte_type:
     ^~~~
gencode.c: In function ‘generateVariableGetter’:
gencode.c:5156:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if (vd->type.u.ed->fqcname != NULL)
            ^
gencode.c:5167:5: note: here
     case byte_type:
     ^~~~
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o extracts.o extracts.c
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o export.o export.c
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o type_hints.o type_hints.c
type_hints.c: In function ‘pyiProperty’:
type_hints.c:761:33: warning: unused variable ‘overloaded’ [-Wunused-variable]
         int implicit_overloads, overloaded;
                                 ^~~~~~~~~~
type_hints.c:761:13: warning: unused variable ‘implicit_overloads’ [-Wunused-variable]
         int implicit_overloads, overloaded;
             ^~~~~~~~~~~~~~~~~~
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o heap.o heap.c
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o parser.o parser.c
gcc -c -pipe -O2 -Wall -W -DNDEBUG -I. -o lexer.o lexer.c
g++  -o sip main.o transform.o gencode.o extracts.o export.o type_hints.o heap.o parser.o lexer.o 
make[1]: Leaving directory '/home/ubuntu/sip-4.19.3/sipgen'
make[1]: Entering directory '/home/ubuntu/sip-4.19.3/siplib'
gcc -c -pipe -fPIC -O2 -Wall -W -DNDEBUG -I. -I/usr/include/python3.6m -o siplib.o siplib.c
siplib.c:20:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:29: recipe for target 'siplib.o' failed
make[1]: *** [siplib.o] Error 1
make[1]: Leaving directory '/home/ubuntu/sip-4.19.3/siplib'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
```

What kind of bug is that, and where should I report it?

**Comment by sincere-music** [comment]
Finally, I found a reliable way to install all the dependencies to frescobaldi on Ubuntu 16.04:

```
sudo apt update
sudo apt install python3-setuptools
sudo easy_install3 pip
sudo [-H] pip3 install PyQt5
sudo apt install python3-pyqt5
sudo apt install python3-pyqt5.qtsvg python3-pyqt5.qtwebkit
cd ~
wget https://pypi.python.org/packages/01/ca/e86c73614a690d778ec9831adee0a728a495f4fb717fab263b5e4887b086/python-ly-0.9.5.tar.gz
tar -xzf python-ly-0.9.5.tar.gz
rm python-ly-0.9.5.tar.gz
cd python-ly-0.9.5
sudo python3 setup.py install
cd ..
wget --show-progress https://github.com/wbsoft/frescobaldi/releases/download/v3.0.0/frescobaldi-3.0.0.tar.gz
tar -xzf frescobaldi-3.0.0.tar.gz
rm frescobaldi-3.0.0.tar.gz
cd frescobaldi-3.0.0
sudo python3 setup.py install
cd ..
sudo apt install pkg-config
sudo apt install libpoppler-qt5-1
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/p/python-poppler-qt5/python3-poppler-qt5_0.24.2-1build1_amd64.deb
sudo dpkg -i python3-poppler-qt5_0.24.2-1build1_amd64.deb
```

**Comment by fedelibre** [comment]
> You can get the sipdistutils.py from riverbank's mercurial server, i.e. [from here](https://www.riverbankcomputing.com/hg/sip/file/14685a6e736e/sipdistutils.py). It is self-contained. Just place it into your Python site-packages folder ...

I confirm it works. Here's a two commands example:

```
wget https://www.riverbankcomputing.com/hg/sip/raw-file/tip/sipdistutils.py
cp sipdistutils.py .virtualenvs/frescobaldi/lib/python3.6/site-packages/
```

**Comment by fedelibre** [comment]
`sipdistutils.py` has been [removed from the sip repository](https://www.riverbankcomputing.com/hg/sip/rev/f43d97c3bf7f) as part of *legacy stuff*.

It should now be downloaded from here:

    wget https://www.riverbankcomputing.com/hg/sip/raw-file/79f89221765d/sipdistutils.py

**Comment by fedelibre** [comment]
IIUC, SIP v5 should fix this problem, see this message from a Riverbank developer two months ago:
http://python.6.x6.nabble.com/SIP-sipdistutils-py-not-installed-td5252485.html

**Comment by AiyionPrime** [comment]
Well, welcome to 2020 everyone.
Installing this in a virtualenv still breaks -.-'

**Comment by davidecappellaro** [comment]
> Well, welcome to 2020 everyone.
> Installing this in a virtualenv still breaks -.-'

I recently successfully managed it working by using colab notebook by google and

```
!apt-get install python3-poppler-qt5
import popplerqt5
```

**Comment by seth4618** [comment]
This bug still exists if you follow the pip install route, but it does work via the apt-get route.  tested on ubuntu 18.04

**Comment by Aens** [comment]
This bug happens on Windows 10, and I'm not even using a virtualenv to install it. Fails both through PyCharm and CMD

**Comment by lbartoletti** [comment]
sipdistuils has been removed from sip5. Any works on this issue?

**Comment by coder202** [comment]
> > Well, welcome to 2020 everyone.
> > Installing this in a virtualenv still breaks -.-'
> 
> I recently successfully managed it working by using colab notebook by google and
> 
> ```
> !apt-get install python3-poppler-qt5
> import popplerqt5
> ```

On Fedora it's:
`sudo dnf install python3-poppler-qt5`

**Comment by jeanas** [comment]
This issue is outdated; we don't use the legacy `sipdistutils` anymore.
